{
	"name" : "PKM POLIBATAM",
	"author" : "Teknik Informatika",
	"version" : "1.0",
	"summary" : "WEB PKM POLIBATAM",
	"depends" : [],
	'data': [
        'security/pkm_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'views/pengajuan_judul_views.xml',
        'views/pengajuan_views.xml',
        'views/jenis_pkm_views.xml',
        'views/res_users_views.xml',
        'views/api_security_views.xml',
        'wizard/wizard_assign_reviewer_views.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
}